// <auto-generated />
using System;
using CVBuilder.Infrastructure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CVBuilder.Infrastructure.Migrations
{
    [DbContext(typeof(CVBuilderDataContext))]
    [Migration("20251105045408_UpdateDatabaseV2")]
    partial class UpdateDatabaseV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.EducationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gpa")
                        .HasColumnType("text");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserCvId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserCvId");

                    b.ToTable("EducationItem");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.ExperienceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("End")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserCvId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserCvId");

                    b.ToTable("ExperienceItem");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PersonalInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonalInfoId");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.PersonalInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserCvId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserCvId")
                        .IsUnique();

                    b.ToTable("PersonalInfo");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.ProjectItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Achievements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("text");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserCvId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserCvId");

                    b.ToTable("ProjectItem");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.SkillItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkillSetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillSetId");

                    b.ToTable("SkillItem");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.SkillSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserCvId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserCvId")
                        .IsUnique();

                    b.ToTable("SkillSet");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.TemplateCv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("TemplateCvs");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.UserCv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResumeTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("UserCvs");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.EducationItem", b =>
                {
                    b.HasOne("Elios.CVBuilder.Domain.Models.UserCv", "UserCv")
                        .WithMany("EducationItems")
                        .HasForeignKey("UserCvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCv");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.ExperienceItem", b =>
                {
                    b.HasOne("Elios.CVBuilder.Domain.Models.UserCv", "UserCv")
                        .WithMany("ExperienceItems")
                        .HasForeignKey("UserCvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCv");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.Link", b =>
                {
                    b.HasOne("Elios.CVBuilder.Domain.Models.PersonalInfo", "PersonalInfo")
                        .WithMany("Links")
                        .HasForeignKey("PersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalInfo");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.PersonalInfo", b =>
                {
                    b.HasOne("Elios.CVBuilder.Domain.Models.UserCv", "UserCv")
                        .WithOne("PersonalInfo")
                        .HasForeignKey("Elios.CVBuilder.Domain.Models.PersonalInfo", "UserCvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCv");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.ProjectItem", b =>
                {
                    b.HasOne("Elios.CVBuilder.Domain.Models.UserCv", "UserCv")
                        .WithMany("ProjectItems")
                        .HasForeignKey("UserCvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCv");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.SkillItem", b =>
                {
                    b.HasOne("Elios.CVBuilder.Domain.Models.SkillSet", "SkillSet")
                        .WithMany("SkillItems")
                        .HasForeignKey("SkillSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillSet");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.SkillSet", b =>
                {
                    b.HasOne("Elios.CVBuilder.Domain.Models.UserCv", "UserCv")
                        .WithOne("SkillSet")
                        .HasForeignKey("Elios.CVBuilder.Domain.Models.SkillSet", "UserCvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCv");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.UserCv", b =>
                {
                    b.HasOne("Elios.CVBuilder.Domain.Models.TemplateCv", "Template")
                        .WithMany("UserCvs")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.PersonalInfo", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.SkillSet", b =>
                {
                    b.Navigation("SkillItems");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.TemplateCv", b =>
                {
                    b.Navigation("UserCvs");
                });

            modelBuilder.Entity("Elios.CVBuilder.Domain.Models.UserCv", b =>
                {
                    b.Navigation("EducationItems");

                    b.Navigation("ExperienceItems");

                    b.Navigation("PersonalInfo");

                    b.Navigation("ProjectItems");

                    b.Navigation("SkillSet");
                });
#pragma warning restore 612, 618
        }
    }
}
